export const ADD_CATEGORY = 'ADD_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const HANDLE_CHECKBOX_CHANGE = 'HANDLE_CHECKBOX_CHANGE';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const HANDLE_CATEGORY_CHECKBOX_CHANGE =
  'HANDLE_CATEGORY_CHECKBOX_CHANGE';
export const REMOVE_PRODUCTS_FROM_CATEGORY = 'REMOVE_PRODUCTS_FROM_CATEGORY';
